name: tliny
description: bazaar project.

publish_to: 'none'

version: 0.3.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  intl:
  flutter_svg:
  responsive_sizer:
  device_preview:
  flutter_dotenv:
  enum_to_string:
  logger:
  collection:

  hooks_riverpod:
  flutter_hooks:
  riverpod_annotation:
  riverpod:

  json_annotation: ^4.9.0
  freezed_annotation:

  google_fonts:
  google_sign_in:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  firebase_analytics:
  firebase_app_check:
  firebase_messaging:
  firebase_performance:
  cloud_functions:
  firebase_crashlytics:

  path_provider:
  image_picker:
  image_picker_for_web:
  crop_your_image:
  file_picker:
  image:
  cached_network_image:

  uuid:

  retrofit:
  dio:

  font_awesome_flutter:
  flutter_multi_formatter:
  http:
  horizontal_data_table:
  package_info_plus:
  fluttertoast:
  # shared_preferences: ^2.0.15
  # js: ^0.6.8
  url_launcher:
  # modal_bottom_sheet: ^2.1.2
  # stripe_sdk: ^5.0.0-nullsafety.1
  # flutter_stripe_web: ^2.1.1
  # flutter_stripe: ^7.0.0
  # stripe_checkout: ^1.0.0
  universal_html:
  barcode:
  barcode_widget:
  mobile_scanner:
  carousel_slider:
  grouped_list:
  encrypt:
  base58check:
  pdf:
  printing:
  flutter_native_splash:
  go_router:
  flutter_gen:

  flutter_riverpod: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint:
  riverpod_lint:
  build_runner:
  json_serializable: ^6.9.5
  freezed:
  riverpod_generator:
  retrofit_generator:
  dependency_validator:
  go_router_builder:
  mockito:
  fake_cloud_firestore:

  firebase_auth_platform_interface: any
flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/img/
    - assets/img/icon.png
    - assets/files/TLINY_terms.txt
    - assets/files/TLINY_commerce.txt
  fonts:
    - family: Melanthios
      fonts:
        - asset: assets/fonts/Melanthios/Melanthios.otf
    # - family: BIZUDPMincho
    #   fonts:
    #     - asset: assets/fonts/BIZUDPMincho/BIZUDPMincho-Regular.ttf
    #     - asset: assets/fonts/BIZUDPMincho/BIZUDPMincho-Bold.ttf
    #       weight: 700
    # - family: NotoSuns
    #   fonts:
    #     - asset: assets/fonts/NotoSuns/NotoSansJP-Regular.ttf
    #     - asset: assets/fonts/NotoSuns/NotoSansJP-Bold.ttf
    #       weight: 700
    # - family: SocialIcons
    #   fonts:
    #     - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

flutter_gen:
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: '#F6F6E5'
  image: 'assets/img/icon.png'
  color_dark: '#262626'
  image_dark: 'assets/img/icon.png'
  fullscreen: true
  web: true
  web_image_mode: center
  # android_12:
  #   icon_background_color: '#F6F6E5'
  #   image: 'assets/img/icon.png'
  #   icon_background_color_dark: '#262626'
  #   image_dark: 'assets/img/icon.png'
