// Mocks generated by Mockito 5.4.5 from annotations
// in tliny/test/unit/viewmodels/usage_history_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:tliny/src/data/model/ticket_model.dart' as _i2;
import 'package:tliny/src/data/repository/ticket_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTicket_0 extends _i1.SmartFake implements _i2.Ticket {
  _FakeTicket_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TicketRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTicketRepository extends _i1.Mock implements _i3.TicketRepository {
  MockTicketRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i2.Ticket>> watchAllTicket() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllTicket, []),
            returnValue: _i4.Stream<List<_i2.Ticket>>.empty(),
          )
          as _i4.Stream<List<_i2.Ticket>>);

  @override
  _i4.Stream<List<_i2.Ticket>> watchTickets(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchTickets, [uid]),
            returnValue: _i4.Stream<List<_i2.Ticket>>.empty(),
          )
          as _i4.Stream<List<_i2.Ticket>>);

  @override
  _i4.Stream<_i2.Ticket> watchTicket(String? uid, String? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTicket, [uid, ticketId]),
            returnValue: _i4.Stream<_i2.Ticket>.empty(),
          )
          as _i4.Stream<_i2.Ticket>);

  @override
  _i4.Future<_i2.Ticket> searchTicket(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#searchTicket, [id]),
            returnValue: _i4.Future<_i2.Ticket>.value(
              _FakeTicket_0(this, Invocation.method(#searchTicket, [id])),
            ),
          )
          as _i4.Future<_i2.Ticket>);

  @override
  _i4.Future<List<_i2.Ticket>> readAllTicket() =>
      (super.noSuchMethod(
            Invocation.method(#readAllTicket, []),
            returnValue: _i4.Future<List<_i2.Ticket>>.value(<_i2.Ticket>[]),
          )
          as _i4.Future<List<_i2.Ticket>>);

  @override
  _i4.Future<List<_i2.Ticket>> readTicket(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#readTicket, [uid]),
            returnValue: _i4.Future<List<_i2.Ticket>>.value(<_i2.Ticket>[]),
          )
          as _i4.Future<List<_i2.Ticket>>);

  @override
  _i4.Future<String> createTicket(_i2.Ticket? ticket) =>
      (super.noSuchMethod(
            Invocation.method(#createTicket, [ticket]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createTicket, [ticket]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> updateTicket(_i2.Ticket? ticket) =>
      (super.noSuchMethod(
            Invocation.method(#updateTicket, [ticket]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#updateTicket, [ticket]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> updateTicketField(
    String? ticketId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTicketField, [ticketId, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTicket(String? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTicket, [ticketId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> testTicket(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#testTicket, [uid]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);
}
