// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxmJJFB5Sp2lk2F-cJ7yKLs7Csp3ngBic',
    appId: '1:736590453040:web:a4125c7a199f8e22cd10f5',
    messagingSenderId: '736590453040',
    projectId: 'tliny-c9630',
    authDomain: 'tliny-c9630.firebaseapp.com',
    storageBucket: 'tliny-c9630.appspot.com',
    measurementId: 'G-DPTLBYP1H5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPVidOcCiBtpj9Mwm9e2_STlUbA6OhuPQ',
    appId: '1:736590453040:ios:1d94bc3ef08c18eecd10f5',
    messagingSenderId: '736590453040',
    projectId: 'tliny-c9630',
    storageBucket: 'tliny-c9630.appspot.com',
    iosClientId: '736590453040-2fpunln7gljjoaviks28upfq138bn7g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tliny',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPVidOcCiBtpj9Mwm9e2_STlUbA6OhuPQ',
    appId: '1:736590453040:ios:1d94bc3ef08c18eecd10f5',
    messagingSenderId: '736590453040',
    projectId: 'tliny-c9630',
    storageBucket: 'tliny-c9630.appspot.com',
    iosClientId: '736590453040-2fpunln7gljjoaviks28upfq138bn7g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tliny',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHy5eRQ7fqhrcktk4-Ck0UXwek5tDy_hg',
    appId: '1:736590453040:android:94b02e3c23b2e383cd10f5',
    messagingSenderId: '736590453040',
    projectId: 'tliny-c9630',
    storageBucket: 'tliny-c9630.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPjCNW0jtMzmIsxdUZxJJJt9ZR1t0pECo',
    appId: '1:736590453040:web:3c66100e985694fccd10f5',
    messagingSenderId: '736590453040',
    projectId: 'tliny-c9630',
    authDomain: 'tliny-c9630.firebaseapp.com',
    storageBucket: 'tliny-c9630.appspot.com',
    measurementId: 'G-PXP1C91BE5',
  );

}