// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGh2hgPptvftSpCbooC6B0JlvF2buRTpc',
    appId: '1:312506082989:web:c9afeda5018001cd450824',
    messagingSenderId: '312506082989',
    projectId: 'tliny-sample',
    authDomain: 'tliny-sample.firebaseapp.com',
    databaseURL:
        'https://tliny-sample-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tliny-sample.appspot.com',
    measurementId: 'G-65ZMZD8S4V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMDuKR6Dick0HCGZSiN55vXl5bzFwB5yw',
    appId: '1:312506082989:ios:d71d0879776e2e27450824',
    messagingSenderId: '312506082989',
    projectId: 'tliny-sample',
    databaseURL:
        'https://tliny-sample-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tliny-sample.appspot.com',
    iosClientId:
        '312506082989-1umb0hv1bkcvg8rspecjr6v3eicrgaj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tliny',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMDuKR6Dick0HCGZSiN55vXl5bzFwB5yw',
    appId: '1:312506082989:ios:d71d0879776e2e27450824',
    messagingSenderId: '312506082989',
    projectId: 'tliny-sample',
    databaseURL:
        'https://tliny-sample-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tliny-sample.appspot.com',
    iosClientId:
        '312506082989-1umb0hv1bkcvg8rspecjr6v3eicrgaj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tliny',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf93IBNSI6tfN76hilPJ6Jw2OPbY1IwGA',
    appId: '1:312506082989:android:84101f58a7eddd02450824',
    messagingSenderId: '312506082989',
    projectId: 'tliny-sample',
    databaseURL:
        'https://tliny-sample-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tliny-sample.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoQSxALGity4uWeKYIvSQ2GgOto6qS3tY',
    appId: '1:312506082989:web:405d7646fcb1f0f6450824',
    messagingSenderId: '312506082989',
    projectId: 'tliny-sample',
    authDomain: 'tliny-sample.firebaseapp.com',
    databaseURL:
        'https://tliny-sample-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tliny-sample.appspot.com',
    measurementId: 'G-PQBNM3YP5T',
  );
}
