// Mocks generated by Mockito 5.4.6 from annotations
// in tliny/test/widget/product_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cloud_firestore/cloud_firestore.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tliny/src/data/model/product_model.dart' as _i2;
import 'package:tliny/src/data/repository/product_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProduct_0 extends _i1.SmartFake implements _i2.Product {
  _FakeProduct_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentReference_1<T extends Object?> extends _i1.SmartFake
    implements _i3.DocumentReference<T> {
  _FakeDocumentReference_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i4.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i2.Product>> streamProducts(_i2.GenreType? genre) =>
      (super.noSuchMethod(
            Invocation.method(#streamProducts, [genre]),
            returnValue: _i5.Stream<List<_i2.Product>>.empty(),
          )
          as _i5.Stream<List<_i2.Product>>);

  @override
  _i5.Stream<List<_i2.Product>> streamProgramProducts(
    _i2.ProductQueryParameter? queryParameter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#streamProgramProducts, [queryParameter]),
            returnValue: _i5.Stream<List<_i2.Product>>.empty(),
          )
          as _i5.Stream<List<_i2.Product>>);

  @override
  _i5.Future<List<_i2.Product>> programProducts(String? programId) =>
      (super.noSuchMethod(
            Invocation.method(#programProducts, [programId]),
            returnValue: _i5.Future<List<_i2.Product>>.value(<_i2.Product>[]),
          )
          as _i5.Future<List<_i2.Product>>);

  @override
  _i5.Stream<List<_i2.Product>> watchProducts() =>
      (super.noSuchMethod(
            Invocation.method(#watchProducts, []),
            returnValue: _i5.Stream<List<_i2.Product>>.empty(),
          )
          as _i5.Stream<List<_i2.Product>>);

  @override
  _i5.Stream<_i2.Product> watchProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#watchProduct, [productId]),
            returnValue: _i5.Stream<_i2.Product>.empty(),
          )
          as _i5.Stream<_i2.Product>);

  @override
  _i5.Future<List<_i2.Product>> readProducts() =>
      (super.noSuchMethod(
            Invocation.method(#readProducts, []),
            returnValue: _i5.Future<List<_i2.Product>>.value(<_i2.Product>[]),
          )
          as _i5.Future<List<_i2.Product>>);

  @override
  _i5.Future<String> createProduct(_i2.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#createProduct, [product]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createProduct, [product]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> updateProduct(_i2.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#updateProduct, [product]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> deleteProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [productId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Product> getProduct(String? docRef) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [docRef]),
            returnValue: _i5.Future<_i2.Product>.value(
              _FakeProduct_0(this, Invocation.method(#getProduct, [docRef])),
            ),
          )
          as _i5.Future<_i2.Product>);

  @override
  _i5.Future<List<String>> createProductsBatch(List<_i2.Product>? products) =>
      (super.noSuchMethod(
            Invocation.method(#createProductsBatch, [products]),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<void> updateProductsBatch(List<_i2.Product>? products) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductsBatch, [products]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteProductsBatch(List<String>? productIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductsBatch, [productIds]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Product>> searchProducts({
    String? keyword,
    _i2.GenreType? genre,
    String? programId,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [], {
              #keyword: keyword,
              #genre: genre,
              #programId: programId,
              #limit: limit,
            }),
            returnValue: _i5.Future<List<_i2.Product>>.value(<_i2.Product>[]),
          )
          as _i5.Future<List<_i2.Product>>);

  @override
  _i5.Stream<_i2.Product> watchProductDoc(
    _i3.DocumentReference<_i2.Product>? productDocRef,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchProductDoc, [productDocRef]),
            returnValue: _i5.Stream<_i2.Product>.empty(),
          )
          as _i5.Stream<_i2.Product>);

  @override
  _i3.DocumentReference<_i2.Product> getProductDocRef(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductDocRef, [productId]),
            returnValue: _FakeDocumentReference_1<_i2.Product>(
              this,
              Invocation.method(#getProductDocRef, [productId]),
            ),
          )
          as _i3.DocumentReference<_i2.Product>);

  @override
  _i3.DocumentReference<_i2.Product> getProductDocRefFromPath(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getProductDocRefFromPath, [path]),
            returnValue: _FakeDocumentReference_1<_i2.Product>(
              this,
              Invocation.method(#getProductDocRefFromPath, [path]),
            ),
          )
          as _i3.DocumentReference<_i2.Product>);

  @override
  _i5.Future<_i2.Product?> getProductOnce(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductOnce, [productId]),
            returnValue: _i5.Future<_i2.Product?>.value(),
          )
          as _i5.Future<_i2.Product?>);
}
